# Generated by Django 2.1.3 on 2018-11-13 12:46

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraCategory',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extra',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.ExtraCategory'),
        ),
    ]
