# Generated by Django 2.1.3 on 2018-11-13 12:46

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('available_crusts', models.ManyToManyField(blank=True, to='pizza.Crust')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PizzaComponent',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pizza.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('metric', models.IntegerField(help_text='Pizza size in CM', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pizzacomponent',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, to='pizza.Size'),
        ),
        migrations.AlterUniqueTogether(
            name='pizzacomponent',
            unique_together={('pizza', 'topping')},
        ),
    ]
