# Generated by Django 2.1.3 on 2018-11-13 12:47

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0001_initial'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('address', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderComponent',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('amount', models.IntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.PizzaComponent')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uid', utils.models.IDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mid', utils.models.IDField(blank=True, db_index=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete')),
                ('amount', models.IntegerField(default=1)),
                ('crust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza.Crust')),
                ('extra', models.ForeignKey(blank=True, help_text='Not to use together with pizza fields', null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.Extra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_orders.Order')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza.Pizza')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza.Size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordercomponent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='customer_orders.OrderItem'),
        ),
        migrations.AlterUniqueTogether(
            name='ordercomponent',
            unique_together={('item', 'component')},
        ),
    ]
